# Generated by Django 3.1.1 on 2020-09-30 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_user_id_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='id_admin',
            new_name='is_admin',
        ),
    ]
