# Generated by Django 3.1.1 on 2020-09-30 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20200930_0813'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
